[tool.poetry]
name = "active-learning-demos"
version = "0.1.0"
description = ""
authors = ["yx <yangxue.cs@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
